package com.polylab.doctors.common.constants;

public final class DoctorConstants {
    public static final String TABLE_NAME = "tbl_Empleado";
    public static final String EMPLOYEE_ID = "idEmpleado";
    public static final String PROFESSION_ID = "idProfesiones";
    public static final String CREATION_USER_ID = "idUsuarioCreacion";
    public static final String DELETION_USER_ID = "idUsuarioEliminacion";
    public static final String MODIFICATION_USER_ID = "idUsuarioModificacion";
    public static final String CREATION_DATE = "fechaCreacion";
    public static final String MODIFICATION_DATE = "fechaModificacion";
    public static final String DELETION_DATE = "fechaEliminacion";
    public static final String RESIDENCE_MUNICIPALITY_ID = "idMunicipioRes";
    public static final String BIRTH_MUNICIPALITY_ID = "idMunicipioNac";
    public static final String BIRTH_DEPARTMENT_ID = "idDepartamentoNac";
    public static final String RESIDENCE_DEPARTMENT_ID = "idDepartamentoRes";
    public static final String BIRTH_COUNTRY_ID = "idPaisNac";
    public static final String RESIDENCE_COUNTRY_ID = "idPaisRes";
    public static final String IDENTIFICATION_TYPE_ID = "idIdentificacion";
    public static final String MARITAL_STATUS_ID = "idEstadoCivil";
    public static final String GENDER_ID = "idSexo";
    public static final String NATIONALITY_ID = "idNacionalidad";
    public static final String IDENTIFICATION_NUMBER = "numIdentificacion";
    public static final String INSS_NUMBER = "numINSS";
    public static final String MINSA_CODE = "codMinsa";
    public static final String FIRST_NAME = "primerNombre";
    public static final String MIDDLE_NAME = "segundoNombre";
    public static final String LAST_NAME = "primerApellido";
    public static final String SECOND_LAST_NAME = "segundoApellido";
    public static final String BIRTH_DATE = "fechaNac";
    public static final String AGE_AT_ENTRY = "edadIngreso";
    public static final String EMAIL = "email";
    public static final String HOME_ADDRESS = "direccionDomiciliar";
    public static final String HOME_PHONE = "telefonoDomiciliar";
    public static final String MOBILE_PHONE = "telefonoMovil";
    public static final String CONTRACT_DATE = "fechaContrato";
    public static final String PHOTO_URL = "urlFoto";
    public static final String ACTIVE = "activo";
    public static final String STATUS = "estado";
}
