= Status Codes

*HTTP* defines these standard status codes that can be used to convey the results of a client’s request.
The status codes are divided into five categories.

- *1xx: Informational* – Communicates transfer protocol-level information.
- *2xx: Success* – Indicates that the client’s request was accepted successfully.
- *3xx: Redirection* – Indicates that the client must take some additional action in order to complete their request.
- *4xx: Client Error* – This category of error status codes points the finger at clients.
- *5xx: Server Error* – The server takes responsibility for these error status codes.

== Examples

200 (OK) It indicates that the REST API successfully carried out whatever action the client requested and that no more specific code in the 2xx series is appropriate.
(GET ALL / GET BY ID)

201 (Created) (SAVE)

202 (Accepted)

204 (No Content) (DELETED)

301 (Moved Permanently)

302 (Found)

303 (See Other)

304 (Not Modified)

400 (Bad Request)

401 (Unauthorized)

(403) (Forbidden)

(500) (Internal Server Error)